# Generated by Django 4.2.4 on 2023-09-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_rename_tipo_blog_blog_tema_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrar_usuario',
            options={'verbose_name_plural': 'Usuarios Registrados'},
        ),
    ]
