# Generated by Django 4.2.4 on 2023-09-08 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_avatar_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='image',
            new_name='img',
        ),
    ]
