# Generated by Django 4.2.4 on 2023-09-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_page_delete_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='subtitulo_page',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='page',
            name='nombre_page',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='page',
            name='tema_page',
            field=models.CharField(max_length=150),
        ),
    ]
