# Generated by Django 4.2.4 on 2023-09-12 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_page_subtitulo_page_alter_page_nombre_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='subtitulo_page',
        ),
    ]
